// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Episode = { id: number, number: number, name: string | null, image: string, season_number: number, };
