// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TMDBData } from "./TMDBData";
import type { TVDBData } from "./TVDBData";

export type Media = { "kind": "Movie" } & TMDBData | { "kind": "Series" } & TVDBData;
