// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MovieDetails = { id: number, original_title: string, poster_path: string, overview: string, release_date: string, };
