// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { tmdb_api_key: string, tvdb_api_key: string, tvdb_api_pin: string, makemkv_path: string, output_directory: string, sftp_hostname: string, sftp_username: string, sftp_password: string, sftp_movie_path: string, sftp_tvshow_path: string, sftp_anime_path: string, };
