// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaType } from "./MediaType";

export type Sftp = { local_path: string, remote_path: string, file_path: string, media_type: MediaType, split_path?: string, };
