// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TitleProgress = { title_index: number, current: bigint, total: bigint | null, max: bigint, };
