// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Title = { index: number, name: string | null, chapters: number | null, duration: string | null, size_bytes: number | null, playlist: string | null, segment_map: string | null, file_name: string | null, };
