// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TMDBData = { id: number, title: string, poster_path: string | null, release_date: string | null, };
