// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";
import type { Season } from "./Season";

export type TVDBData = { id: string, name: string | null, image_url: string | null, year: string | null, seasons: Array<Season>, episodes: Array<Episode>, };
